apiVersion: v1
kind: Secret
metadata:
  name: nst-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://postgres:postgres@nst-postgres-service:5432/nst_events?schema=public'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  POSTGRES_DB: 'nst_events'
  JWT_SECRET: 'placeholder-k8s-jwt-secret'
  GOOGLE_CLIENT_ID: 'placeholder-google-client-id'
  GOOGLE_CLIENT_SECRET: 'placeholder-google-client-secret'
  EXPO_PUSH_TOKEN: 'placeholder-expo-push-token'
