/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-subdued': '#1A1A1A',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1b1b',
        'surface-container': '#1f1f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        primary: '#b7c4ff',
        'primary-fixed': '#dde1ff',
        'primary-container': '#0052ff',
        'on-primary-container': '#dfe3ff',
        'primary-hover': '#dce3f0',
        'on-primary': '#002682',
        secondary: '#7bd0ff',
        'secondary-fixed': '#c4e7ff',
        'secondary-fixed-dim': '#7bd0ff',
        'secondary-container': '#00a6e0',
        'on-secondary': '#00354a',
        tertiary: '#c0c7d3',
        'on-tertiary': '#2a313b',
        'tertiary-container': '#5f6671',
        'on-tertiary-container': '#dee4f1',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#c3c5d9',
        outline: '#8d90a2',
        'outline-variant': '#434656',
        'border-hairline': '#434656',
        'border-dark': '#1f1f1f',
        background: '#131313',
      },
      fontFamily: {
        'headline-lg': ['Syne_700Bold'],
        'headline-md': ['Syne_700Bold'],
        'headline-sm': ['Syne_700Bold'],
        'display-hero': ['Syne_800ExtraBold'],
        'body-lg': ['Inter_400Regular'],
        'body-md': ['Inter_400Regular'],
        'body-sm': ['Inter_400Regular'],
        'meta-label': ['JetBrainsMono_600SemiBold', 'JetBrainsMono_700Bold'],
        'meta-badge': ['JetBrainsMono_700Bold'],
        'meta-code': ['JetBrainsMono_500Medium'],
      },
      spacing: {
        'space-2xs': '2px',
        'space-xs': '4px',
        'space-sm': '8px',
        'space-md': '12px',
        'space-base': '16px',
        'space-lg': '20px',
        'space-xl': '24px',
        'space-2xl': '32px',
        'space-3xl': '48px',
        'screen-gutter': '16px',
        'touch-target-min': '48px',
      },
      borderRadius: {
        'none': '0',
        'sm': '2px',
        'md': '4px',
        'lg': '8px',
        'full': '9999px'
      }
    },
  },
  plugins: [],
}
