const darkColors = {
  surface: '#131313',
  surfaceSubdued: '#1A1A1A',
  surfaceContainerLowest: '#0e0e0e',
  surfaceContainerLow: '#1b1b1b',
  surfaceContainer: '#1f1f1f',
  surfaceContainerHigh: '#2a2a2a',
  surfaceContainerHighest: '#353535',
  primary: '#b7c4ff',
  primaryFixed: '#dde1ff',
  primaryContainer: '#0052ff',
  onPrimaryContainer: '#dfe3ff',
  primaryHover: '#dce3f0',
  onPrimary: '#002682',
  secondary: '#7bd0ff',
  secondaryFixed: '#c4e7ff',
  secondaryFixedDim: '#7bd0ff',
  secondaryContainer: '#00a6e0',
  onSecondary: '#00354a',
  tertiary: '#c0c7d3',
  onTertiary: '#2a313b',
  tertiaryContainer: '#5f6671',
  onTertiaryContainer: '#dee4f1',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  onSurface: '#e2e2e2',
  onSurfaceVariant: '#c3c5d9',
  outline: '#8d90a2',
  outlineVariant: '#434656',
  borderHairline: '#434656',
  borderDark: '#1f1f1f',
};

const lightColors = {
  surface: '#fbfbfb',
  surfaceSubdued: '#f4f4f4',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f7f7f7',
  surfaceContainer: '#f0f0f0',
  surfaceContainerHigh: '#e8e8e8',
  surfaceContainerHighest: '#e0e0e0',
  primary: '#0046d1',
  primaryFixed: '#003eb3',
  primaryContainer: '#dde1ff',
  onPrimaryContainer: '#001454',
  primaryHover: '#0036a1',
  onPrimary: '#ffffff',
  secondary: '#006a8f',
  secondaryFixed: '#007bb3',
  secondaryFixedDim: '#008cc0',
  secondaryContainer: '#c4e7ff',
  onSecondary: '#ffffff',
  tertiary: '#4b525d',
  onTertiary: '#ffffff',
  tertiaryContainer: '#dee4f1',
  onTertiaryContainer: '#131821',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#410002',
  onSurface: '#131313',
  onSurfaceVariant: '#434656',
  outline: '#74777f',
  outlineVariant: '#c4c6d0',
  borderHairline: '#d1d3df',
  borderDark: '#d1d3df',
};

export const theme = {
  colors: darkColors, // Default export remains dark for non-react usage (if any)
  typography: {
    syneBold: 'Syne_700Bold',
    syneExtraBold: 'Syne_800ExtraBold',
    interRegular: 'Inter_400Regular',
    interMedium: 'Inter_500Medium',
    interSemiBold: 'Inter_600SemiBold',
    monoRegular: 'JetBrainsMono_400Regular',
    monoMedium: 'JetBrainsMono_500Medium',
    monoBold: 'JetBrainsMono_700Bold',
  },
  spacing: {
    '2xs': 2,
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    touchMin: 48,
  },
  borderRadius: {
    none: 0,
    sm: 2,
    md: 4,
    lg: 8,
  },
};

export { darkColors, lightColors };
